* repdisplay.inc

DISPLAY "#### START: repdisplay.inc";

*OPTION
* gdpindic:


DISPLAY
  WFAVGX
  WFAVGXP
  WFAVGXPP
  TFPSCALX
  TFPSCALXP
  CPIX
  CPIXP
  DPIX
  DPIXP
  EGX
  EGXP
  EHX
  EHXP
  EXRX
  EXRXP
  SAVFX
  SAVFXP
  QGSCALX
  QGSCALXP
  GOVRECGDPX
* GOVRECGDPXP
  GOVSPNDGDPX
* GOVSPNDGDPXP
  GPRIMDEFX
  GPRIMDEFXP
  ISCALX
  ISCALXP
  DKAX
  DKAXP
  SAVX
  SAVXP
  MPSSCALX
  MPSSCALXP
  MPSADJX
* MPSADJXP


  MPSX
  MPSXP
  NGOVPAYGDPX
* NGOVPAYGDPXP
  PAX
  PAXP
  PDDX
  PDDXP
  PDSX
  PDSXP
  PEX
  PEXP
  PKX
  PKXP
  PMX
  PMXP
  PQSX
  PQSXP
  PQDX
  PQDXP
  PVAX
  PVAXP
  pwex
  pwexp
  pwmx
  pwmxp

  PXX
  PXXP
  QAX
  QAXP
  QAXPP
  QDX
  QDXP
  QEX
  QEXP
  QFSX
  QFSXP
  QFSXPP
  QFX
  QFXP
  QFXPP
  QGX
  QGXP
  QGXPP
  QHX
  QHXP
  QHXPP
  
  QINTX
  QINTXP
  QINVX
  QINVXP
  QMX
  QMXP
  QQX
  QQXP
  QTX
* QTXP
  QXX
  QXXP
  PREXRX
  PREXRXP
  PREXRXPP
  REXRX
  REXRXP
  REXRXPP
  RGDPFCX
  RGDPFCXP
  RGPRIMDEFX
  RGPRIMDEFXP
  TASCALX
* TASCALXP
  TAX
* TAXP
  TESCALX
* TESCALXP
  TEX
* TEXP
  TFSCALX
* TFSCALXP
  TFPX
  TFPXP
  TMSCALX
* TMSCALXP
  TMX
* TMXP
  TQSCALX
* TQSCALXP
  TQX
* TQXP
  TRIIX
  TRIIXP
  TRNSFRX
* TRNSFRXP
  TYSCALX
  TYSCALXP
  TYX
  TYXP
  UERATX
  UERATXP
  UERATXPP
  WALRASX
  WFDISTX
  WFDISTXP
  WFX
  WFXP
  YFX
  YFXP
  YGX
  YGXP
  YIFX
* YIFXP
  YIX
  YIXP

  SUBCSCALX
* SUBCSCALXP
  SUBCX
* SUBCXP
  TVACSCALX
* TVACSCALXP
  TVACX
  TVACXP
  

  FBORX
  FBORXP
  FDEBTX
  FDEBTXP
  GBORX
  GBORXP
  GDEBTX
  GDEBTXP
  NFFGX
  NFFGXP
  NFFINSSCALX            
  NFFINSSCALXP            
  NFFINSX              
  NFFINSXP          
  NDFGX                 
  NDFGXP                  
  RNDFGX
  RNDFGXP

  GDPMPX
  SAVGX
  SAVGXP
  RSAVGX
  RSAVGXP
  
* reportes calculados
  qgbX
  wfrealX
  wfaX
  wfarealX

  modsolstat
  
  gdpindic
  gdpindicXP
  gdpindicXPP
  
  SIMSAM
  simsambalchk
  errsimsambalchk

  taxstruc
  sectorstruc
  fiscalindic
  bopindic
  
  
  facdemstruc
  actvashr

  ev
  cv
  
  MACROSAM2
  macrosam2balchk
  
  sectorindic
  sectorindicXP
  sectorindicXPP
  
  demstruc
  incomestruc
  
  popX  
  popXP 
  popXPP

  QTRSTX       
  QTRSTXP      
  QTRSTXPP     
  QTRSTSCALX   
  QTRSTSCALXP  
  QTRSTSCALXPP 
  
  TRSMRECX     
  TRSMRECXP    
  TRSMRECXPP   

  
;

DISPLAY "#### END: repdisplay.inc";